
language: java

jdk:

  - openjdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2
after_success:
  - mvn clean test
  - bash <(curl -s https://codecov.io/bash) -t y5kxbcxoRFn0DIefnIEjfftqg9tzGaEbF